# Travis file
# See https://docs.travis-ci.com/user/languages/r/

language: r
cache: packages

r_binary_packages: 
  - covr
  - dplyr
  - tibble
  - stringr
  - broom
  - openxlsx
  - readxl
  - readr
  - tidyr
  - httr
  - jsonlite
  - effsize
  - crayon

after_success:
  - Rscript -e 'library(covr); codecov()'
